name: WordPress CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      rollback_version:
        description: 'Artifact version to rollback to (optional)'
        required: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  JAVA_HOME: "/usr/lib/jvm/java-1.8.0-amazon-corretto"

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build and prepare artifacts
        run: |
          echo Entered the build phase...
          echo Build started on `date`
          version=$(git rev-parse --short HEAD)
          timestamp=$(date +"%Y%m%d-%H%M%S")
          artifact_name="fmp-advisor-cms-$version-$timestamp.zip"
          echo "$FMP_ENV" > scripts/fmpenv
          echo "$FMP_REGION" > scripts/fmpregion
          echo "Post build phase started"
          mkdir -p artifacts/fadvuk
          cp -PR custom_packages artifacts
          cp -PR forbes-advisor-theme/* artifacts/fadvuk/
          rsync scripts/* --progress artifacts/ --exclude prod
          cd artifacts
          zip -r $artifact_name *
          aws s3 cp $artifact_name s3://arti-storage/${{ secrets.FMP_ENV }}/${{ secrets.FMP_REGION }}/$artifact_name


  deploy:
    needs: build_and_upload_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t ecdsa 44.202.19.252 >> ~/.ssh/known_hosts

      - name: Download artifact from S3
        run: aws s3 sync s3://arti-storage/${{ secrets.FMP_REGION }}/${{ secrets.FMP_ENV }}/ ./artifact-folder

      - name: Deploy to EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo chown -R ubuntu:ubuntu /var/www/html/; sudo chmod -R 775 /var/www/html/; sudo mkdir -p /var/www/html/wp-content/themes"
          rsync -avz --delete --exclude='.git*' --exclude='.env' --exclude='.github' -e 'ssh -i private_key.pem -o StrictHostKeyChecking=no' --chmod=D2775,F664 --chown=ubuntu:ubuntu ./artifact-folder/ ubuntu@44.202.19.252:/var/www/html/wp-content/themes/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "unzip -o \$(ls /var/www/html/wp-content/themes/*.zip | tail -n 1) -d /var/www/html/wp-content/themes/"
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo chown -R www-data:www-data /var/www/html/; sudo chmod -R 755 /var/www/html/"
      - name: Run scripts on EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo systemctl stop apache2"
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo systemctl start apache2"
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo chown -R www-data:www-data /var/www/html/; sudo chmod -R 755 /var/www/html/"

  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rollback_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t ecdsa 44.202.19.252 >> ~/.ssh/known_hosts

      - name: Get the most recent artifact from S3
        id: latest_artifact
        run: |
          latest_artifact=$(aws s3api list-objects --bucket arti-storage --query "reverse(sort_by(Contents, &LastModified))[0].Key" --output=text --prefix "${{ secrets.FMP_REGION }}/${{ secrets.FMP_ENV }}/")
          echo "Latest artifact: $latest_artifact"
          echo "::set-output name=artifact_path::$latest_artifact"

      - name: Download the most recent artifact from S3
        run: aws s3 cp s3://arti-storage/${{ steps.latest_artifact.outputs.artifact_path }} ./artifact-folder 

      - name: Deploy specified artifact to EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@54.144.17.44 "sudo chown -R ubuntu:ubuntu /var/www/html/; sudo chmod -R 775 /var/www/html/; sudo mkdir -p /var/www/html/wp-content/themes"
          unzip ./artifact-folder/* -d ./unzipped-artifact
          rsync -avz --delete --exclude='.git*' --exclude='.env' --exclude='.github' -e 'ssh -i private_key.pem -o StrictHostKeyChecking=no' --chmod=D2775,F664 --chown=ubuntu:ubuntu ./unzipped-artifact/ ubuntu@54.144.17.44:/var/www/html/wp-content/themes/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@54.144.17.44 "sudo chown -R www-data:www-data /var/www/html/; sudo chmod -R 755 /var/www/html/"

      - name: Restart services on EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo systemctl stop apache2"
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@44.202.19.252 "sudo systemctl start apache2"    
