name: WordPress CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, mysql, pdo_mysql, zip
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

  deploy:
    needs: install_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_KEY: 'ec2-44-201-255-103.compute-1.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDS5fqlD+BJYpj3oOkHlmnjV6YHmqYW+X8HzRu9Td91c4i3vHjmazGw28IJtM6NNd6PM1qGHQqCEHxtVGBQludAME2dNOKzXkX1lt5Wx6s4R1Jzx3QHuUr8rYT3/1wu/cZhbYhv2Vhx4RjwNyEKcXsPNgLT4WkoFM3xcF2U3LXB86lVFxgG4ulQx2RZkY6g8Q4nVfslSRWJy8LF5/x07xPpOt1UOuenadD+v6YPu+FT5x1rl4M78M3+QxTIokhEux7xNy+oqG/M/pSeNKTEuj37Kgx93hAqh3ZqWgNH+fEHMymMsxrSQ4UZDPlqtTBvdrRvRLFTsfJ3YLwCZC1Vmjh86bbZQitczSNKrnEttCO0Z8ER8Bgva2lslF5uI6pfBNwCbR6GPfK9oBzv21qcuURazxyu6kkC3Dhj9/V4sZf3OtuuZujDc/5g1J+AKehEHV+uS151hJGGya7k9L+TyvNcB+TpoF8pUs+I6NmmWvuw/pHbtHjVPoSD62HtZnw+oKs='
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          echo "$HOST_KEY" >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2 instance
        run: |
          sudo rsync -avz --delete --exclude='.git*' --exclude='.env' --exclude='.github' -e 'ssh -i private_key.pem' . ubuntu@ec2-44-201-255-103.compute-1.amazonaws.com:/var/www/html/
          
      - name: Create
