name: WordPress CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, mysql, pdo_mysql, zip
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

  deploy:
    needs: install_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ec2-3-80-138-158.compute-1.amazonaws.com >> ~/.ssh/known_hosts || true
      - name: Deploy to EC2 instance
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='.env' --exclude='.github' -e 'ssh -i private_key.pem' . ec2-3-80-138-158.compute-1.amazonaws.com:/var/www/html/
      - name: Create artifact folder
        run: mkdir artifact-folder

      - name: Copy WordPress files to artifact folder
        run: cp -r /var/www/html/* artifact-folder/

      - name: Upload artifact to S3
        run: |
          aws s3 sync ./artifact-folder s3://test--wordpress
      - name: Test deployment
        run: |
          curl http://ec2-3-84-248-98.compute-1.amazonaws.com/

