name: WordPress CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, mysql, pdo_mysql, zip
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

  deploy:
    needs: install_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ec2-3-80-138-158.compute-1.amazonaws.com >> ~/.ssh/known_hosts || true
      - name: Deploy to EC2 instance
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='.env' --exclude='.github' -e 'ssh -i private_key.pem' . ubuntu@ec2-3-80-138-158.compute-1.amazonaws.com:/var/www/html/

      - name: Setup WordPress
        env:
          DB_NAME: wordpress_db
          DB_USER: wordpress_user
          DB_PASSWORD: your_password
          EC2_INSTANCE: ubuntu@ec2-3-80-138-158.compute-1.amazonaws.com
        run: |
          ssh -i private_key.pem $EC2_INSTANCE "wget https://wordpress.org/latest.tar.gz"
          ssh -i private_key.pem $EC2_INSTANCE "tar -xzvf latest.tar.gz"
          ssh -i private_key.pem $EC2_INSTANCE "sudo mv wordpress/* /var/www/html/"
          ssh -i private_key.pem $EC2_INSTANCE "sudo chown -R www-data:www-data /var/www/html/"
          ssh -i private_key.pem $EC2_INSTANCE "sudo find /var/www/html/ -type d -exec chmod 755 {} \\;"
          ssh -i private_key.pem $EC2_INSTANCE "sudo find /var/www/html/ -type f -exec chmod 644 {} \\;"
          ssh -i private_key.pem $EC2_INSTANCE "mysql -u root -p -e \"CREATE DATABASE $DB_NAME; CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD'; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'; FLUSH PRIVILEGES;\""
          ssh -i private_key.pem $EC2_INSTANCE "sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php"
          ssh -i private_key.pem $EC2_INSTANCE "sudo sed -i \"s/'database_name_here'/'$DB_NAME'/g; s/'username_here'/'$DB_USER


