name: WordPress CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Manually trigger a rollback'
        required: false 


env:
  AWS_REGION: us-east-1

jobs:
  build_and_upload_artifact:
    if: ${{ github.event.inputs.rollback != 'true' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and prepare artifacts
        
        run: |
          artifact_name="fmp-advisor-cms.zip"
          mkdir -p artifacts/fadvuk
          cp -PR custom_packages artifacts
          cp -PR forbes-advisor-theme/* artifacts/fadvuk/
          rsync scripts/* --progress artifacts/ --exclude prod
          cd artifacts
          zip -r $artifact_name *
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: fmp-advisor-cms
          path: artifacts/fmp-advisor-cms.zip
          retain-on-branch: '*'
  deploy:
    needs: build_and_upload_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t ecdsa 54.175.222.11 >> ~/.ssh/known_hosts
      - name: Download artifact from GitHub
        uses: actions/download-artifact@v2
        with:
          name: fmp-advisor-cms
          path: artifact-folder

      - name: Deploy index.html to EC2 instance
        run: |
          unzip -p artifact-folder/fmp-advisor-cms.zip custom_packages/index.html > index.html
          scp -i private_key.pem -o StrictHostKeyChecking=no ./index.html ubuntu@54.175.222.11:/tmp/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@54.175.222.11 "\
          sudo mv /tmp/index.html /var/www/html/; \
          sudo chown www-data:www-data /var/www/html/index.html; \
          sudo chmod 644 /var/www/html/index.html"
  
  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.rollback == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rollback to previous commit
        run: |
          git fetch origin main
          git checkout main

          last_commit_sha=$(git rev-parse HEAD~1)

          if [ -z "$last_commit_sha" ]; then
            echo "No previous commit found"
            exit 1
          fi

          git reset --hard $last_commit_sha
          git push --force
